# Generated by Django 5.1 on 2024-10-30 19:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=255)),
                ('clave_proyecto', models.CharField(max_length=100, unique=True)),
                ('empresa', models.CharField(max_length=255)),
                ('estatus', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
