# Generated by Django 5.1 on 2024-11-11 16:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=255)),
                ('clave_proyecto', models.CharField(max_length=100, unique=True)),
                ('empresa', models.CharField(max_length=255)),
                ('estatus', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ganancia_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
