# Generated by Django 5.1 on 2024-11-08 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_fin_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='ganancia_estimada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='presupuesto_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='progreso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
