# Generated by Django 5.1 on 2024-09-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='clave_proyecto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
