# Generated by Django 5.1 on 2024-09-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectos_clave_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='clave_proyecto',
            field=models.CharField(max_length=100),
        ),
    ]
