# Generated by Django 5.1 on 2024-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_proyectos_iva_alter_proyectos_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='clave_proyecto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
