# Generated by Django 5.1 on 2024-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('placas', models.CharField(max_length=60)),
                ('combustible', models.CharField(choices=[('GASOLINE', 'Gasolina'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Eléctrico')], default='GASOLINE', max_length=30)),
                ('valor_original', models.FloatField()),
            ],
        ),
    ]
