# Generated by Django 5.1 on 2025-01-10 17:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_presupuesto', models.CharField(max_length=50, unique=True)),
                ('nombre_proyecto', models.CharField(max_length=80)),
                ('cliente', models.CharField(max_length=40)),
                ('responsable', models.CharField(max_length=40)),
                ('contacto', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('presupuesto_json', models.JSONField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_presupuesto', to='presupuestos.datospresupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioUnitarioPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.TextField()),
                ('unidad', models.CharField(choices=[('servicio', 'Servicio'), ('m2', 'Metros cuadrados'), ('ml', 'Metros lineales'), ('pza', 'Pieza')], max_length=30)),
                ('materiales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('examenes_med_dc3', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('equipos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('epp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_indirecto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_financiamiento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('meses_financiamiento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('utilidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_unitario', to='presupuestos.datospresupuesto')),
            ],
        ),
    ]
