# Generated by Django 5.1 on 2025-01-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospresupuesto',
            name='slug',
            field=models.SlugField(default='new-slug', unique=True),
        ),
    ]
