# Generated by Django 5.1 on 2025-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_datospresupuesto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospresupuesto',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=80), unique=True),
        ),
    ]
