# Generated by Django 5.1 on 2025-01-10 20:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_alter_preciounitariopresupuesto_meses_financiamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciounitariopresupuesto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='preciounitariopresupuesto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
