# Generated by Django 5.1 on 2025-01-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_alter_datospresupuesto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospresupuesto',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
