# Generated by Django 5.1 on 2025-01-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_datospresupuesto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preciounitariopresupuesto',
            old_name='id_presupuesto',
            new_name='presupuesto',
        ),
    ]
