# Generated by Django 5.1 on 2025-01-08 23:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_rename_id_presupuesto_preciounitariopresupuesto_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciounitariopresupuesto',
            name='meses_financiamiento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
    ]
