# Generated by Django 5.1 on 2024-09-22 19:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=100)),
                ('infonavit', models.BooleanField(default=False)),
                ('imss', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencias', models.BooleanField(default=True)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='proyectos.proyectos')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='empleados.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.FloatField()),
                ('infonavit', models.FloatField()),
                ('imss', models.FloatField()),
                ('isn', models.FloatField()),
                ('asistencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salario', to='empleados.asistencias')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salario', to='empleados.empleados')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salario', to='proyectos.proyectos')),
            ],
        ),
    ]
