# Generated by Django 5.1 on 2024-09-22 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 9, 22, 19, 49, 39, 139134, tzinfo=datetime.timezone.utc)),
        ),
    ]
