# Generated by Django 5.1 on 2024-09-22 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_asistencias_fecha_alter_salario_imss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='empleado',
        ),
        migrations.AddField(
            model_name='empleados',
            name='apellido_materno',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empleados',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empleados',
            name='nombres',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 9, 22, 21, 41, 19, 661776)),
        ),
    ]
