# Generated by Django 5.1 on 2024-09-22 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_remove_empleados_empleado_empleados_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 9, 22, 21, 41, 35, 233968)),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido_materno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido_paterno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombres',
            field=models.CharField(max_length=255),
        ),
    ]
