# Generated by Django 5.1 on 2024-09-23 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_alter_asistencias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 9, 23, 10, 15, 17, 401090)),
        ),
    ]
