# Generated by Django 5.1 on 2024-09-23 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_asistencias_horas_extras_empleados_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
