# Generated by Django 5.1 on 2024-09-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0014_salario_horas_extras_salario_salario_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salario',
            old_name='isn',
            new_name='isr',
        ),
    ]
