# Generated by Django 5.1 on 2024-09-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0015_rename_isn_salario_isr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='asistencias',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='salario_base',
        ),
    ]
