# Generated by Django 5.1 on 2024-09-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0017_salario_lote_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='lote',
            field=models.IntegerField(editable=False),
        ),
    ]
