# Generated by Django 5.1 on 2024-10-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0018_alter_salario_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='rfc',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
