# Generated by Django 5.1 on 2024-10-30 19:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos_y_vehiculos', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('tiempo_renta', models.CharField(choices=[('RENTA_MENSUAL', 'renta mensual'), ('RENTA_SEMANAL', 'renta semanal'), ('RENTA_DIARIA', 'renta diaria'), ('PROPIEDAD', 'Propiedad')], default='RENTA_MENSUAL', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_equipos', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_generales', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('imss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('infonavit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lote', models.IntegerField(unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_mano_obra', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_materiales', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_seguridad', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_combustible', models.FloatField()),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('proveedor', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_vehiculos', to='proyectos.proyectos')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='equipos_y_vehiculos.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('referencia', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='proyectos.proyectos')),
            ],
        ),
    ]
