# Generated by Django 5.1 on 2024-09-22 19:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos_y_vehiculos', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('tiempo_renta', models.CharField(choices=[('RENTA_MENSUAL', 'renta mensual'), ('RENTA_SEMANAL', 'renta semanal'), ('RENTA_DIARIA', 'renta diaria'), ('PROPIEDAD', 'Propiedad')], default='RENTA_MENSUAL', max_length=100)),
                ('monto', models.FloatField()),
                ('iva', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_equipos', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('iva', models.FloatField()),
                ('notas', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_generales', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.FloatField()),
                ('imss', models.FloatField()),
                ('infonavit', models.FloatField()),
                ('isn', models.FloatField()),
                ('isr', models.FloatField()),
                ('monto', models.FloatField(default=0)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_mano_obra', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('iva', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_materiales', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('iva', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_seguridad', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_combustible', models.FloatField()),
                ('monto', models.FloatField()),
                ('iva', models.FloatField()),
                ('proveedor', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_vehiculos', to='proyectos.proyectos')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='equipos_y_vehiculos.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('referencia', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 9, 22, 19, 41, 28, 441504, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='proyectos.proyectos')),
            ],
        ),
    ]
