# Generated by Django 5.1 on 2025-08-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_categoriagasto_lote_gasto_nominaempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='comprador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
