# Generated by Django 5.1 on 2024-09-22 22:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_gastosequipos_fecha_alter_gastosequipos_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
