# Generated by Django 5.1 on 2024-09-23 21:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_gastosequipos_iva_alter_gastosequipos_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmanoobra',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
