# Generated by Django 5.1 on 2024-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_gastosmanoobra_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosmanoobra',
            name='lote',
            field=models.IntegerField(),
        ),
    ]
